version: 2

jobs:
    # Build Cyclus
    build:
        docker:
            - image: cyclus/cyclus-deps
        working_directory: ~/cyclus
        steps:
            # Ensure your image has git (required by git to clone via SSH) so that CircleCI can clone your repo
            - run: apt-get -qq update; apt-get -y install git openssh-client
            - checkout
            - run:
                name: Build Docker Image
                command: |
                    python install.py -j 2 --build-type=Release --core-version 999999.999999 \
                    -DBLAS_LIBRARIES="/opt/conda/lib/libblas.so" \
                    -DLAPACK_LIBRARIES="/opt/conda/lib/liblapack.so"
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - save_cache:
                key: v1-repo-{{ checksum ".circle-sha" }}
                paths:
                  - /root


    d3ploy_build:
        docker:
            - image: cyclus/cyclus-deps
        working_directory: ~/
        steps:
            - run: git clone https://github.com/ergs/d3ploy -b develop
            - run:
                name: build d3ploy
                command: |
                    cd d3ploy
                    python setup.py install
    
    unit_test:
        docker:
            - image: cyclus/cyclus-deps
        working_directory: ~/d3ploy
        steps:
            - run:
                name: solver unit tests
                command: pytest ./tests/solver_unit_tests.py
