version: 2

jobs:

    cyclus_master:
      docker:
        - image: cyclus/cyclus-deps
      working_directory: /root
      steps:
        - run: apt-get -qq update; apt-get -y install git openssh-client
        - run:
            name: save SHA to a file
            command: echo $CIRCLE_SHA1 > .circle-sha
        - restore_cache:
          keys:
            - v1-repo--{{ checksum ".circle-sha" }}
        - run:
          name: checkout cyclus master
          command: |
            git clone https://github.com/cyclus/cyclus.git
            cd cyclus
            git fetch --all
            git checkout master
        - run:
          name: build cyclus
          command: |
            cd cyclus
            python install.py -j 2 --build-type=Release --core-version 999999.999999 \
                    -DBLAS_LIBRARIES="/opt/conda/lib/libblas.so" \
                    -DLAPACK_LIBRARIES="/opt/conda/lib/liblapack.so"


    cycamore_master: ## Cycamore/master against Cyclus/dev
        docker:
            - image: cyclus/cyclus-deps
        working_directory: /root
        steps:
            # Ensure your image has git (required by git to clone via SSH) so that CircleCI can clone your repo
            - run: apt-get -qq update; apt-get -y install git openssh-client
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - restore_cache:
                keys:
                  - v1-repo-{{ checksum ".circle-sha" }}
            - run:
                name: Checkout Cycamore Master
                command: |
                    git clone https://github.com/cyclus/cycamore.git
                    cd cycamore
                    git fetch --all
                    git checkout master
            - run:
                name: Build Cycamore
                command: |
                    cd cycamore
                    python install.py -j 2 --build-type=Release \
                    -DBLAS_LIBRARIES="/opt/conda/lib/libblas.so" \
                    -DLAPACK_LIBRARIES="/opt/conda/lib/liblapack.so"
    
    build:
      docker:
          - image: cyclus/cyclus-deps
      working_directory: ~/d3ploy
      steps:
        - run: apt-get -qq update; apt-get -y install git openssh-client
        - checkout
        - run:
            name: build d3ploy
            command: python setup.py install

    unit_test:
        docker:
            - image: cyclus/cyclus-deps
        working_directory: ~/d3ploy
        steps:
            - run:
                name: solver unit tests
                command: pytest solver_unit_tests.py
