version: 2

jobs:

    build:
      docker:
        - image: cyclus/cycamore
      working_directory: ~/d3ploy
      steps:
        - run: apt-get -qq update; apt-get -y install git openssh-client
        - checkout
        - run:
            name: build d3ploy
            command: python setup.py install
        - run:
            name: save SHA to a file
            command: echo $CIRCLE_SHA1 > .circle-sha
        - save_cache:
            key: v1-repo-{{ checksum ".circle-sha" }}
            paths:
              - /root


    unit_test:
        docker:
            - image: cyclus/cycamore
        working_directory: ~/d3ploy
        steps:
          - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
          - restore_cache:
                keys:
                  - v1-repo-{{ checksum ".circle-sha" }}
          - run:
                name: solver unit tests
                command: |
                    pip install -U pytest
                    python setup.py install
                    pytest ./tests/solver_unit_tests.py

    
    install_d3ploy_dep:
        docker:
            - image: cyclus/cycamore
        working_directory: ~/d3ploy
        steps:
            - run: 
                name: conda install
                command: |
                    conda install -c bashtage arch -y
                    conda install -c anaconda statsmodels -y
                    conda install -c anaconda scipy -y
            - run:
                name: save SHA to a file
                command: echo $CIRCLE_SHA1 > .circle-sha
            - save_cache:
                key: v1-repo-{{ checksum ".circle-sha" }}
                paths:
                  - /root

    

workflows:
        version: 2
        build_and_test:
            jobs:
                - build
                - install_d3ploy_dep
                - unit_test:
                    requires:
                        - install_d3ploy_dep
                        - build
